### ISSUE TITLE
Cannot connect to same host with a different port

### ISSUE THREAD

**Issue by rahul0705** [flackr/circ#329] opened 2014-10-27 12:58 UTC
If I try to connect to irc.example.com with port 7000 and then make a connection to irc.example.com with port 6777 it won't do anything

**Comment by BrandonG777** [comment] 2015-02-18 20:23
Same here but I would like to make multiple connections to the same server on the same port but supplying different usernames and passwords.

**Comment by snook** [comment] 2015-04-04 05:46
Duplicate of https://github.com/flackr/circ/issues/276

**Comment by rahul0705** [comment] 2015-07-02 02:36
Any idea when #276 or any of the other issues will be fixed?

**Closed** 2019-12-16 20:05 UTC
