### ISSUE TITLE
CIRC doesn't render after recovering from a crash

### ISSUE THREAD

**Issue by krruzic** [flackr/circ#345] opened 2015-06-15 09:02 UTC
I mean a crash of Chrome OS. The window has decorations but is otherwise completely transparent and requires a restart. Not that big of an issue I know, but it is annoying.

**Comment by flackr** [comment] 2015-06-15 15:05
I've seen this too. As far as I know there is nothing CIRC could be doing to cause this and I've filed http://crbug.com/282324 but there are no concrete repro steps. If you have a reproducible failure please comment on the chromium bug there, thanks! I'm closing this since I do not believe it's something that can be fixed in CIRC.

**Closed by flackr** 2015-06-15 15:05 UTC

**Comment by krruzic** [comment] 2015-06-17 13:44
Hmm, interesting. Glad it's known at least. Yeah, hard to reproduce... I wonder if any other apps are affected.
